spring:
  data:
    mongodb:
      username: firass
      password: agfirass100
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
